/**
 * File Manager
 * File Manager Web API for Angular Application
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OsInfo } from './osInfo';
import { RamUsage } from './ramUsage';
import { Usage } from './usage';

export interface SystemStatus { 
    cpu: Usage;
    disk: Usage;
    memory: RamUsage;
    os: OsInfo;
}